config/routes.rb
RedmineApp::Application.routes.draw do

	resources :leave_requests do
		member do
			get 'submit'
			get 'unsubmit'
		end
		collection do
			get 'leave_length'
			get 'leave_issue_description'
		end
		resource :leave_status, :except => [:show]
		resources :leave_votes, :except => [:show]
	end

	resources :users do
		resource :leave_preference do
			get 'notification'
			get 'manage_pending_days'
		end
	end

	resources :leave_preferences, :only => [:index] do
		collection do
			match '/bulk_edit', :to => 'leave_preferences#bulk_edit', :via => [:get, :post]
			put '/bulk_update', :to => 'leave_preferences#bulk_update'
			get '/clear_filters', :to => 'leave_preferences#clear_filters'
		end
	end

	resources :leave_rules

	resources :projects do
		match 'leave_management_rules/edit', :to => 'leave_management_rules#edit', :via => [:get, :post], as: :leave_management_rules_edit
		match 'leave_management_rules/update', :to => 'leave_management_rules#update', :via => [:get, :post], as: :leave_management_rules_update
		match 'leave_management_rules/enable', :to => 'leave_management_rules#enable', :via => [:get], as: :leave_management_rules_enable
		match 'leave_management_rules/disable', :to => 'leave_management_rules#disable', :via => [:get], as: :leave_management_rules_disable
		
		match 'leave_administrators/edit', :to => 'leave_administrators#edit', :via => [:get, :post], as: :leave_administrators_edit
		match 'leave_administrators/update', :to => 'leave_administrators#update', :via => [:get, :post], as: :leave_administrators_update
		match 'leave_administrators/clear', :to => 'leave_administrators#clear', :via => [:get], as: :leave_administrators_clear
	end

	get '/leave_approvals', :to => 'leave_approvals#index'
	get '/leave_timeline', :to => 'leave_timelines#show'
	get '/projects/:project_id/leave_timeline', :to => 'leave_timelines#show_project'
	get '/leave_management_rules/:project_id/show_metrics', :to => 'leave_management_rules#show_metrics', as: :leave_rules_show_metrics

	get '/leave_feedbacks/new', :to => 'leave_requests#feedback_new', as: :leave_feedbacks_new
	post '/leave_feedbacks/send', :to => 'leave_requests#feedback_send', as: :leave_feedbacks_send

	
end

app/models/leave_administrator.rb
class LeaveAdministrator < ActiveRecord::Base
  unloadable

  default_scope {
    project_ids = pluck(:project_id)
    system_leave_project_ids = Project.where(id: project_ids).system_leave_projects.pluck(:id)
    joins(:user, :project).where(users: {status: 1}, projects: {status: 1, id: system_leave_project_ids}) }

  belongs_to :user
  belongs_to :project

  validates :user_id, presence: true
  validates :project_id, presence: true
end

app/controllers/leave_administrators_controller.rb
class LeaveAdministratorsController < ApplicationController
  unloadable
  before_action :find_project
  before_action :authorize

  helper :leave_management_rules

  def edit
    @leave_administrators = LeaveAdministrator.where(project: @project).pluck(:user_id)
  end

  def update
    if params[:leave_administrator_ids]
      LeaveAdministrator.unscoped.destroy_all(project: @project)
      user_ids = User.all.active.where(id: params[:leave_administrator_ids]).pluck(:id)
      user_ids.each do |admin_id|
        l = LeaveAdministrator.new(project: @project, user_id: admin_id)
        l.save
      end
    end
  end

  def clear
    LeaveAdministrator.unscoped.destroy_all(project: @project)
    render :update
  end


  private

  def find_project
    @project ||= Project.find(params[:project_id])
  end

end

app/views/leave_administrators/_edit_modal.html.erb
<h3 class="title"><%= l(:leave_administrators_edit_title) %></h3>

<%= form_tag project_leave_administrators_update_path, :id => :leave_administrators, :remote => true, :method => :post do %>
  <%= render :partial => 'form' %>
  <p><small><%= l(:leave_hint_ctrl_clic) %></small></p>

  <% if @leave_administrators.any? %>
    <p><small><%= link_to l(:leave_administrators_clear), project_leave_administrators_clear_path(@project.id), :remote => true, :class => "icon icon-del", :onclick => "hideModal(this);" %></small></p>
  <% end %>

  <p class="buttons">
    <%= submit_tag l(:button_submit), :name => nil, :onclick => "hideModal(this);" %>
    <%= submit_tag l(:button_cancel), :name => nil, :onclick => "hideModal(this);", :type => 'button' %>
  </p>
<% end %>

app/views/leave_administrators/_form.html.erb
<p><small><%= l(:leave_administrators_form_info) %></small></p>
<table align="center">
  <tr>
    <td>
      <%= select_tag 'leave_administrator_ids', user_not_contractor_options_for_select(@leave_administrators), :multiple => true, :size => 7 %>
    </td>
  </tr>
</table>

app/views/leave_administrators/_link_to_leave_administrators.html.erb
<% administrators_set = @project.leave_administrators.any? %>

<% if administrators_set %>
  <%= link_to l(:leave_administrators_edit_project_title), project_leave_administrators_edit_path(@project.id), :remote => true, :class => "icon icon-edit" %>
<% else %>
  <strong><%= link_to l(:leave_administrators_set_project_title), project_leave_administrators_edit_path(@project.id), :remote => true, :class => "icon icon-add", :style => "color: red;" %></strong>
<% end %>

app/views/leave_administrators/edit.js.erb
$('#ajax-modal').html('<%= escape_javascript(render :partial => 'leave_administrators/edit_modal') %>');
showModal('ajax-modal', '600px');

app/views/leave_administrators/update.js.erb
$("#leave-admins").html('<%= escape_javascript(render :partial => '/leave_administrators/link_to_leave_administrators', locals: {project: @project}) %>')

$.ajax({
      url: '<%= leave_rules_show_metrics_path(@project) %>',
      cache: false,
      beforeSend: function(){
        $('#leave-rules-metrics').html('<%= escape_javascript(render :partial => '/leave_commons/loading') %>');
      },
      success: function(data){
        $("#leave-rules-metrics").html(data);
      }

});