config/routes.rb
RedmineApp::Application.routes.draw do

	resources :leave_requests do
		member do
			get 'submit'
			get 'unsubmit'
		end
		collection do
			get 'leave_length'
			get 'leave_issue_description'
		end
		resource :leave_status, :except => [:show]
		resources :leave_votes, :except => [:show]
	end

	resources :users do
		resource :leave_preference do
			get 'notification'
			get 'manage_pending_days'
		end
	end

	resources :leave_preferences, :only => [:index] do
		collection do
			match '/bulk_edit', :to => 'leave_preferences#bulk_edit', :via => [:get, :post]
			put '/bulk_update', :to => 'leave_preferences#bulk_update'
			get '/clear_filters', :to => 'leave_preferences#clear_filters'
		end
	end

	resources :leave_rules

	resources :projects do
		match 'leave_management_rules/edit', :to => 'leave_management_rules#edit', :via => [:get, :post], as: :leave_management_rules_edit
		match 'leave_management_rules/update', :to => 'leave_management_rules#update', :via => [:get, :post], as: :leave_management_rules_update
		match 'leave_management_rules/enable', :to => 'leave_management_rules#enable', :via => [:get], as: :leave_management_rules_enable
		match 'leave_management_rules/disable', :to => 'leave_management_rules#disable', :via => [:get], as: :leave_management_rules_disable
		
		match 'leave_administrators/edit', :to => 'leave_administrators#edit', :via => [:get, :post], as: :leave_administrators_edit
		match 'leave_administrators/update', :to => 'leave_administrators#update', :via => [:get, :post], as: :leave_administrators_update
		match 'leave_administrators/clear', :to => 'leave_administrators#clear', :via => [:get], as: :leave_administrators_clear
	end

	get '/leave_approvals', :to => 'leave_approvals#index'
	get '/leave_timeline', :to => 'leave_timelines#show'
	get '/projects/:project_id/leave_timeline', :to => 'leave_timelines#show_project'
	get '/leave_management_rules/:project_id/show_metrics', :to => 'leave_management_rules#show_metrics', as: :leave_rules_show_metrics

	get '/leave_feedbacks/new', :to => 'leave_requests#feedback_new', as: :leave_feedbacks_new
	post '/leave_feedbacks/send', :to => 'leave_requests#feedback_send', as: :leave_feedbacks_send

	
end

app/controllers/leave_management_rules_controller.rb
class LeaveManagementRulesController < ApplicationController
  unloadable
  include LeavesHolidaysManagements
  before_action :find_project
  before_action :authorize

  helper :leave_management_rules
  helper :leave_requests
  include LeaveManagementRulesHelper

  def edit
    unless params[:edit] && params[:edit] == "true"
      session[:management_rule_ids] = nil
    end

    unless params[:management_rule_ids]
      @sender_type = params[:sender_type] || LeavesHolidaysManagements.default_actor_type
      @sender_list_id ||= params[:sender_list_id]
      @sender_exception_id ||= params[:sender_exception_id]

      @action = params[:action_rule] || LeaveManagementRule.actions['is_managed_by'] 
      
      @receiver_type = params[:receiver_type] || LeavesHolidaysManagements.default_actor_type
      @receiver_list_id ||= params[:receiver_list_id]
      @receiver_exception_id ||= params[:receiver_exception_id]
      @backup_receiver_id ||= params[:backup_receiver_id]
      
      @reason_selected = 0
      @reason_selected = params[:reasons_selected] if params[:reasons_selected]

      @reasons_concerned_ids ||= params[:reasons_concerned_id]

    else
      management_rules = LeaveManagementRule.where(id: params[:management_rule_ids], project: @project)
      management_rule_ids = management_rules.pluck(:id)
      sender_exceptions = LeaveExceptionRule.where(leave_management_rule_id: management_rule_ids, actor_concerned: LeaveExceptionRule.actors_concerned[:sender])
      receiver_exceptions = LeaveExceptionRule.where(leave_management_rule_id: management_rule_ids, actor_concerned: LeaveExceptionRule.actors_concerned[:receiver])
      backup_receiver = LeaveExceptionRule.where(leave_management_rule_id: management_rule_ids, actor_concerned: LeaveExceptionRule.actors_concerned[:backup_receiver])
      reasons_concerned = LeaveReasonRule.where(leave_management_rule_id: management_rule_ids)

      @sender_type = management_rules.first.sender_type_form
      @sender_list_id ||= management_rules.pluck(:sender_id)
      @sender_exception_id ||= sender_exceptions.pluck(:user_id)

      @action = LeaveManagementRule.actions[management_rules.first.action]

      @receiver_type = management_rules.first.receiver_type_form
      @receiver_list_id ||= management_rules.pluck(:receiver_id)
      @receiver_exception_id ||= receiver_exceptions.pluck(:user_id)
      @backup_receiver_id ||= backup_receiver.pluck(:user_id)
      @reasons_concerned_ids ||= reasons_concerned.pluck(:issue_id)
      @reason_selected = 0
      @reason_selected = 1 if @reasons_concerned_ids.any?
      session[:management_rule_ids] = management_rule_ids
    end
  end

  def update
    if params[:delete] && params[:delete] == "true" && params[:management_rule_ids] && !params[:management_rule_ids].empty?
        LeaveManagementRule.destroy_all(id: params[:management_rule_ids].map(&:to_i), project: @project)
    else
      if session[:management_rule_ids] && !session[:management_rule_ids].empty?
        LeaveManagementRule.destroy_all(id: session[:management_rule_ids].map(&:to_i), project: @project)
      end
      if params[:sender_list_id] && params[:receiver_list_id]
        @leave_management_rule_errors = []
        params[:sender_list_id].each do |sender_id|
          params[:receiver_list_id].each do |receiver_id|
            @leave_management_rule = LeaveManagementRule.new(project: @project, sender: params[:sender_type].constantize.find(sender_id.to_i), receiver: params[:receiver_type].constantize.find(receiver_id.to_i), action: LeaveManagementRule.actions.select{|k,v| v == params[:action_rule].to_i}.keys.first)
            #if @leave_management_rule.save

              if params[:sender_exception_id]
                params[:sender_exception_id].each do |sender_excpt|
                  LeaveExceptionRule.create(leave_management_rule: @leave_management_rule, actor_concerned: :sender, user: User.find(sender_excpt.to_i))
                end
              end
              if params[:receiver_exception_id]
                params[:receiver_exception_id].each do |receiver_excpt|
                  LeaveExceptionRule.create(leave_management_rule: @leave_management_rule, actor_concerned: :receiver, user: User.find(receiver_excpt.to_i))
                end
              end
              if params[:backup_receiver_id]
                params[:backup_receiver_id].each do |backup_receiver|
                  LeaveExceptionRule.create(leave_management_rule: @leave_management_rule, actor_concerned: :backup_receiver, user: User.find(backup_receiver.to_i))
                end
              end

              @reason_selected = '0'
              @reason_selected = params[:reasons_selected] if params[:reasons_selected]

              if params[:reasons_concerned_id] && @reason_selected == '1'
                params[:reasons_concerned_id].each do |reason|
                  LeaveReasonRule.create(leave_management_rule: @leave_management_rule, issue: Issue.find(reason.to_i))
                end
              end

            #else
            if @leave_management_rule.save
            else
              @leave_management_rule_errors << @leave_management_rule
              return
            end
            #end

          end
        end
      end
      
    end
    session[:management_rule_ids] = nil

  end

  def show_metrics
    render :layout => false
  end

  def index
    respond_to do |format|
      format.html { head 406 }
    end
  end

  def enable
    LeavesHolidaysManagementsModules.enable_leave_management_rules_project(@project)
    redirect_to settings_project_path(@project, 'leave_management')
  end

  def disable
    LeavesHolidaysManagementsModules.disable_leave_management_rules_project(@project)
    redirect_to settings_project_path(@project, 'leave_management')
  end

  private

  def find_project
    @project ||= Project.find(params[:project_id])
  end

  def redirect_to_settings_in_projects
    redirect_to settings_project_path(@project, :tab => 'leave_management')
  end

end

app/helpers/leave_management_rules_helper.rb
module LeaveManagementRulesHelper
  include LeavesHolidaysManagements
  
  def actor_type_options_for_select(selected)
    options = LeavesHolidaysManagements.actor_types
    options_for_select(options, selected)
  end

  # Given an actor, "sender" or "receiver", remove selected from available options for opposite actor.
  def actor_collection_for_select_options(project, actor)
    # Return empty list if actor is not a sender nor a receiver
    return [] unless actor.in?(['sender', 'receiver'])
    # Gets the opposite actor of the actor given sender -> receiver, etc.
    actor_opposite = actor == 'sender' ? 'receiver' : 'sender'

    # Gets the type of the sender/receiver, User or Role
    receiver_type = @receiver_type# || LeavesHolidaysManagements.default_actor_type
    sender_type = @sender_type#|| LeavesHolidaysManagements.default_actor_type

    # If actor is the sender, get sender type. otherwise, get receiver type
    actor_type = actor == 'sender' ? sender_type : receiver_type
    actor_opposite_type = actor_opposite == 'sender' ? sender_type : receiver_type
    # Get a list of roles or users with regards to the actor type provided
    list = project.send(actor_type.underscore + "_list")

    # Get the list of ids already selected previously for the other actor
    list_opposite_ids = actor_opposite == 'sender' ? @sender_list_id : @receiver_list_id
    list_opposite_exception_ids = actor_opposite == 'sender' ? @sender_exception_id : @receiver_exception_id
    list_opposite_exception_ids ||= []
    # if the list is not empty
    if list_opposite_ids
      list_opposite = list_opposite_ids.map{|e| e.to_i}
      if actor_type == actor_opposite_type
        list.delete_if {|l| l.id.in?(list_opposite)}
        return list.map{|l| [l.name, l.id]}
      else
        if actor_opposite_type == 'Role' && actor_type == 'User'
          actor_opposite_roles_selected = Role.where(id: list_opposite).to_a
          actor_opposite_associated_user_ids = project.users_for_roles(actor_opposite_roles_selected).map(&:id)
          list.delete_if {|l| l.id.in?(actor_opposite_associated_user_ids - list_opposite_exception_ids.map(&:to_i))}
          return list.map{|l| [l.name, l.id]}
        end
      end
    end

    return list.map{|l| [l.name, l.id]}.sort_by{|t| t[0]}
  end

  def sender_exception_collection_for_select_options(project)
    return [] if @sender_type != "Role" || !@sender_list_id || @sender_list_id.empty?

    receiver_selected = []
    if @receiver_type == "User" && @receiver_list_id
      receiver_selected_ids = @receiver_list_id.map(&:to_i)
      receiver_selected = User.where(id: receiver_selected_ids)
    end
    sender_roles_selected = Role.where(id: @sender_list_id.map{|e| e.to_i}).to_a
    users_associated_with_roles_selected = project.users_for_roles(sender_roles_selected)
    #return [] if users_associated_with_roles_selected.count == 1
    return (users_associated_with_roles_selected + receiver_selected.select{|u| u.in?(users_associated_with_roles_selected)}).uniq.sort_by(&:name).map{|l| [l.name, l.id]}
  end

  def receiver_exception_collection_for_select_options(project)
    return [] if @receiver_type != "Role" || !@receiver_list_id || @receiver_list_id.empty?

    sender_selected = []
    if @sender_type == "User" && @sender_list_id
      sender_selected_ids = @sender_list_id.map(&:to_i)
      sender_selected = User.where(id: sender_selected_ids)
    end
    receiver_roles_selected = Role.where(id: @receiver_list_id.map{|e| e.to_i}).to_a
    users_associated_with_roles_selected = project.users_for_roles(receiver_roles_selected)
    #return [] if users_associated_with_roles_selected.count == 1
    return (users_associated_with_roles_selected + sender_selected.select{|u| u.in?(users_associated_with_roles_selected)}).uniq.sort_by(&:name).map{|l| [l.name, l.id]}
  end

  def backup_receiver_collection_for_select_options(project)
    return [] if @action.to_i != LeaveManagementRule.actions['is_managed_by']

    sender_selected_ids = []
    if @sender_type == "User" && @sender_list_id
      sender_selected_ids = @sender_list_id.map(&:to_i)
    end

    if @sender_type == "Role" && @sender_list_id
      sender_roles_selected = Role.where(id: @sender_list_id.map(&:to_i)).to_a
      users_associated_with_roles_selected = project.users_for_roles(sender_roles_selected)
      if @sender_exception_id
        sender_exception_ids = @sender_exception_id.map(&:to_i)
        users_associated_with_roles_selected.delete_if{|u| u.id.in?(sender_exception_ids)}
      end
      sender_selected_ids = users_associated_with_roles_selected.map(&:id)
    end

    return User.all.active.where.not(id: sender_selected_ids).sort_by(&:name).map{|l| [l.name, l.id]}
  end

  def action_sender_options_for_select(selected)
    options = LeaveManagementRule.actions.to_a.map{|a| [a[0].humanize, a[1]]}.reverse
    options_for_select(options, selected)
  end

  def user_not_contractor_options_for_select(selected)
    options = User.all.active.not_contractor.sort_by(&:name).map{|l| [l.name, l.id]}
    return options_for_select(options, selected)
  end

  def leave_reasons_rules_specifics(selected)
    issues_ids = []
    issues_ids << RedmineLeavesHolidays::Setting.defaults_settings(:available_reasons_contractors)
    issues_ids << RedmineLeavesHolidays::Setting.defaults_settings(:available_reasons_non_contractors)
    issues = Issue.where(id: issues_ids.flatten.uniq)
    options = issues.map {|a| [a.subject, a.id]}
    return options_for_select(options, selected)
  end

  def leave_reasons_select(selected)
    options_for_select([['All leave reasons', 0], ['Specific Leave Reasons:', 1]], selected)
  end

end

app/views/leave_management_rules/_edit_form.html.erb
<fieldset class="box">
  <p><%= l(:leave_hint_ctrl_clic) %></p>

  <table align="center">
    <tr>
      <td>
       <span title="<%= l(:label_snd_rcv_type_explain) %>" style="cursor: help;"><%= l(:leave_management_sender_type) %>:</span> 
        <p><%= select_tag 'sender_type', actor_type_options_for_select(@sender_type) %></p>
      </td>
      <td>
      <span title="<%= l(:label_sender_explain) %>" style="cursor: help;"><%= l(:leave_management_sender_list) %>:</span> 
        <p><%= select_tag 'sender_list_id', actor_collection_for_select_options(@project, 'sender'), :multiple => true, :size => 10 %>
        </p>
      </td>
      <td>
      <span title="<%= l(:label_action_to_perform_explain) %>" style="cursor: help;"><%= l(:leave_management_action) %>:</span> 
        <p><%= select_tag 'action_rule', action_sender_options_for_select(@action) %></p>
      </td>
      <td>
        <span title="<%= l(:label_snd_rcv_type_explain) %>" style="cursor: help;"><%= l(:leave_management_receiver_type) %>:</span>
        <p><%= select_tag 'receiver_type', actor_type_options_for_select(@receiver_type) %></p>
      </td>
      <td>
        <span title="<%= l(:label_receiver_explain) %>" style="cursor: help;"><%= l(:leave_management_receiver_list) %>:</span> 
        <p><%= select_tag 'receiver_list_id', actor_collection_for_select_options(@project, 'receiver'), :multiple => true, :size => 10 %></p>
      </td>
      <% if @action.to_i == LeaveManagementRule.actions['is_managed_by'] %>
        <td>
          <span title="<%= l(:label_backup_explain) %>" style="cursor: help;"><%= l(:leave_management_backup) %></span>
          <p><%= select_tag 'backup_receiver_id', backup_receiver_collection_for_select_options(@project), :multiple => true, :size => 10 %></p>
        </td>
      <% end %>
      
      <td>
      <div style="display: none">
          <span><%= l(:leave_management_reasons) %>:</span>
          <p><%= select_tag 'reasons_selected', leave_reasons_select(@reason_selected) %></p>
          <% if @reason_selected == 1 %>
            <div id="reasons_div">
          <% else %>
            <div id="reasons_div" style="display: none">
          <% end %>
          <p><%= select_tag 'reasons_concerned_id', leave_reasons_rules_specifics(@reasons_concerned_ids), :multiple => true, :size => 8 %></p>
          </div>
      </div>
      </td>
      
    </tr>
    <tr>
      <td></td>
      <td>
        <% if @sender_type == "Role" && @sender_list_id && @sender_list_id.uniq.size == 1 %>
          <% @sender_options = sender_exception_collection_for_select_options(@project) %>
          <% unless @sender_options.empty? %>
            <div id="sender_exception_div">
            <legend><%= label_tag "sender_exception_id", l(:leave_management_sender_exception) %>:</legend>
            <p><%= select_tag 'sender_exception_id', @sender_options, :multiple => true, :selected => 0, :size => 5 %>
            </p>
            </div>
          <% end %>
        <% end %>
      </td>
      <td></td>
      <td></td>
      <td>
        <% if @receiver_type == "Role" && @receiver_list_id && @receiver_list_id.uniq.size == 1 %>
          <% @receiver_options = receiver_exception_collection_for_select_options(@project) %>
          <% unless @receiver_options.empty? %>
            <div id="receiver_exception_div">
            <legend><%= label_tag "receiver_exception_id", l(:leave_management_receiver_exception) %>:</legend>
            <p><%= select_tag 'receiver_exception_id', @receiver_options, :multiple => true, :selected => 0, :size => 5 %>
            </p>
            </div>
          <% end %>
        <% end %>
      </td>
    </tr>
    
  </table>
  

</fieldset>


<%= javascript_tag do %>
  $(document).ready(function(){


    $('#sender_type, #receiver_type, #sender_list_id, #receiver_list_id, #action_rule, #sender_exception_id, #receiver_exception_id, #reasons_selected').change(function(){
      $.ajax({
        url: '<%= escape_javascript project_leave_management_rules_edit_path(:format => 'js', :edit => params["edit"]) %>',
        type: 'post',
        data: $('#leave_management_rules').serialize()
      });
    });
  });
<% end %>

app/views/leave_management_rules/_edit_modal.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'leaves_holidays', :plugin => 'redmine_leaves_holidays' %>
<% end %>

<h3 class="title"><%= l(:leave_management_rules) %></h3>

<%= form_tag project_leave_management_rules_update_path, :id => :leave_management_rules, :remote => true, :method => :post do %>
  <%= render :partial => 'edit_form' %>
  <p class="buttons">
    <%= submit_tag l(:button_submit), :id => 'leave_management-edit-submit', :onclick => "hideModal(this); $overlay.show();" %>
    <%= submit_tag l(:button_cancel), :name => nil, :onclick => "hideModal(this);", :type => 'button' %>
  </p>
<% end %>

<%= javascript_tag do %>
    var $overlay = $('<div class="ui-widget-overlay"></div>').hide().appendTo('body');
<% end %>

app/views/leave_management_rules/_rules_table.html.erb
<% if LeaveManagementRule.where(project: project).count > 0 %>
  <table class="list">
  <thead>
      <tr>
        <th><%= l(:leave_management_sender) %></th>
        <th><%= l(:leave_management_action) %></th>
        <th><%= l(:leave_management_receiver) %></th>
        <th><%= l(:leave_management_backup) %></th>
        <!-- <th style="display: none"><%= l(:leave_management_reasons) %></th> -->
        <th></th>
      <tr>
  </thead>
  <tbody> 

  
  <% rules_grouped = LeavesHolidaysManagements.deep_group_management_rules(LeaveManagementRule.where(project: project).to_a) %>

  <% unless rules_grouped.empty? %>

    <% rules_grouped.each do |rule_ids| %>
      <% rule_group = LeaveManagementRule.where(id: rule_ids).includes(:sender, :receiver, :leave_exception_rules, :leave_reason_rules).to_a %>
      <% exceptions = rule_group.first.leave_exception_rules.includes(:user) %>
      <% reasons = rule_group.first.leave_reason_rules.includes(:issue) %>
      <tr>
        <td>
          <%= rule_group.map{ |r| r.sender.name }.uniq.join(", ") %>
          <% excp_sender = exceptions.where(actor_concerned: LeaveExceptionRule.actors_concerned['sender']) %>
          <% unless excp_sender.empty? %>
            <% excep_sender_users = excp_sender.map(&:user).map(&:name).uniq %>
            </br><strong><%= l(:leave_management_exception).pluralize(excep_sender_users.count) %>:</strong> <%= excep_sender_users.join(", ") %>
          <% end %>
        </td>

        <td><%= rule_group.map{ |r| r.action.humanize }.uniq.join(", ") %></td>

        <td>
          <%= rule_group.map{ |r| r.receiver.name }.uniq.join(", ") %>
          <% excp_receiver = exceptions.where(actor_concerned: LeaveExceptionRule.actors_concerned['receiver']) %>
          <% unless excp_receiver.empty? %>
            <% excep_receiver_users = excp_receiver.map(&:user).map(&:name).uniq %>
            </br><strong><%= l(:leave_management_exception).pluralize(excep_receiver_users.count) %>:</strong> <%= excep_receiver_users.join(", ") %>
          <% end %>
        </td>
        <td>
          <% backup_receiver = exceptions.where(actor_concerned: LeaveExceptionRule.actors_concerned['backup_receiver']) %>
          <% unless backup_receiver.empty? %>
            <% backup_receiver_users = backup_receiver.map(&:user).map(&:name).uniq %>
            <%= backup_receiver_users.join(", ") %>
          <% end %>
        </td>
        <td style="display: none">
          <% if reasons.any? %>
            <%= reasons.map(&:issue).map(&:subject).join(", ") %>
          <% else %>
            All
          <% end %>
          
        </td>
        <td>
          <%= #rule_ids 
          %>
            <%= link_to l(:button_edit), project_leave_management_rules_edit_path(project, :management_rule_ids => rule_ids, :edit => true), :remote => true, :class => "icon icon-edit" 
            %>
            <%= link_to l(:button_delete), project_leave_management_rules_update_path(project, :management_rule_ids => rule_ids, :delete => true), :remote => true, :class => "icon icon-del" 
            %>
        </td>
      </tr>

    <% end %>
  <% end %>


  </tbody>      
  </table>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/leave_management_rules/create.js.erb
$('#tab-content-leave_management').html('<%= escape_javascript(render :partial => 'projects/leave_management_settings') %>');
hideOnLoad();
hideModal();

app/views/leave_management_rules/edit.js.erb
$('#ajax-modal').html('<%= escape_javascript(render :partial => 'leave_management_rules/edit_modal') %>');
showModal('ajax-modal', '90%');
$('#sender_list_id').html('<%= escape_javascript options_for_select(actor_collection_for_select_options(@project, "sender"), @sender_list_id) %>');
$('#receiver_list_id').html('<%= escape_javascript options_for_select(actor_collection_for_select_options(@project, "receiver"), @receiver_list_id) %>');
$('#sender_exception_id').html('<%= escape_javascript options_for_select(sender_exception_collection_for_select_options(@project), @sender_exception_id) %>');
$('#receiver_exception_id').html('<%= escape_javascript options_for_select(receiver_exception_collection_for_select_options(@project), @receiver_exception_id) %>');
$('#backup_receiver_id').html('<%= escape_javascript options_for_select(backup_receiver_collection_for_select_options(@project), @backup_receiver_id) %>');

 if($('#reasons_selected').val() == "1")
 {
   $('#reasons_div').show();
 }
 else
 {
   $('#reasons_div').hide();
 }
 

app/views/leave_management_rules/show_metrics.html.erb

<% managed_by_leave_admin_people = @project.users_roles_managed_by_leave_admin %>
<div class="splitcontentright">
  <div class="members box">
  <% unless managed_by_leave_admin_people.empty? %>

    <% leave_admins = @project.get_leave_administrators %>

    <% unless leave_admins[:project_defined] %>
       <h3 style="color: red"><%= l(:leave_management_members_managed_by_sys_leave_admins) %> (<%= leave_admins[:users].map(&:name).join(", ") %>):</h3>
    <% else %>
       <h3><%= l(:leave_management_members_managed_by_proj_leave_admins) %> (<%= leave_admins[:users].map(&:name).join(", ") %>):</h3>
    <% end %>

    <% managed_by_leave_admin_people.keys.sort.each do |role| %>
      <p><span class="label"><%= role %>:</span> <%= users_link_to_notification(managed_by_leave_admin_people[role].sort) %></p>
    <% end %>
  <% end %>



  <% no_create_people = @project.users_by_role_who_cant_create_leave_requests %>
  <% unless no_create_people.empty? %>
    <h3><%= l(:leave_management_members_not_allowed_create_leave) %>:</h3>
    <% no_create_people.keys.sort.each do |role| %>
      <p><span class="label"><%= role %>:</span> <%= users_link_to_notification(no_create_people[role].sort) %></p>
    <% end %>
  <% end %>
  </div>
</div>


<% users_by_role = @project.users_by_role_who_can_create_leave_requests %>

<div class="splitcontentleft">
  <% if users_by_role.any? %>
  <div class="members box">
    <h3><%= l(:leave_management_members_details) %></h3>
    <% users_by_role.keys.sort.each do |role| %>
      <p><span class="label"><%= role %>:</span> <%= users_link_to_checked_if_managed_in_project(users_by_role[role].sort, @project) %>
      </p>
    <% end %>
    <h4><%= l(:leave_legend) %>:</h4>
    <p><span class="label"><%= checked_image %></span> <%= l(:leave_management_member_managed_in_project) %></p>
    <p><span class="label"><%= image_tag('toggle_check_amber.png', :plugin => 'redmine_leaves_holidays') %></span> <%= l(:leave_management_member_managed_other_project) %></p>
    <p><span class="label"><%= image_tag('reload.png')  %></span> <%= l(:leave_management_member_managed_by_leave_admin) %></p>
    <p><span class="label"><%= image_tag('hourglass.png', :size => '12x12') %></span> <%= l(:leave_management_member_contractor) %></p>
    <p><span class="label"><%= image_tag('user.png') %></span> <%= l(:leave_management_member_project_leave_admin) %></p>
    <p><span class="label"><%= image_tag('group.png') %></span> <%= l(:leave_management_member_system_leave_admin) %></p>
    <p><span class="label"><%= image_tag('false.png', :size => '12x12') %></span> <%= t(:leave_management_member_not_managed_projects_html) %></p>
    <p><small><%= l(:leave_management_hint) %></small></p>
  </div>
<% end %>
</div>

app/views/leave_management_rules/update.js.erb
$('#table-content').html('<%= escape_javascript(render :partial => '/leave_management_rules/rules_table', locals: {project: @project}) %>');

<% if @leave_management_rule_errors.present? %>
  <% errors = @leave_management_rule_errors.collect {|m| m.errors.full_messages}.flatten.uniq.join(', ') %>
  alert('<%= raw(escape_javascript(l(:notice_failed_to_save_rules, :errors => errors))) %>');
<% end %>

if (typeof $overlay != "undefined") {
  $overlay.hide();
}

$.ajax({
      url: '<%= leave_rules_show_metrics_path(@project) %>',
      cache: false,
      beforeSend: function(){
        $('#leave-rules-metrics').html('<%= escape_javascript(render :partial => '/leave_commons/loading') %>');
      },
      success: function(data){
        $("#leave-rules-metrics").html(data);
      }

});

$('#ajax-indicator').hide();