config/routes.rb
RedmineApp::Application.routes.draw do

	resources :leave_requests do
		member do
			get 'submit'
			get 'unsubmit'
		end
		collection do
			get 'leave_length'
			get 'leave_issue_description'
		end
		resource :leave_status, :except => [:show]
		resources :leave_votes, :except => [:show]
	end

	resources :users do
		resource :leave_preference do
			get 'notification'
			get 'manage_pending_days'
		end
	end

	resources :leave_preferences, :only => [:index] do
		collection do
			match '/bulk_edit', :to => 'leave_preferences#bulk_edit', :via => [:get, :post]
			put '/bulk_update', :to => 'leave_preferences#bulk_update'
			get '/clear_filters', :to => 'leave_preferences#clear_filters'
		end
	end

	resources :leave_rules

	resources :projects do
		match 'leave_management_rules/edit', :to => 'leave_management_rules#edit', :via => [:get, :post], as: :leave_management_rules_edit
		match 'leave_management_rules/update', :to => 'leave_management_rules#update', :via => [:get, :post], as: :leave_management_rules_update
		match 'leave_management_rules/enable', :to => 'leave_management_rules#enable', :via => [:get], as: :leave_management_rules_enable
		match 'leave_management_rules/disable', :to => 'leave_management_rules#disable', :via => [:get], as: :leave_management_rules_disable
		
		match 'leave_administrators/edit', :to => 'leave_administrators#edit', :via => [:get, :post], as: :leave_administrators_edit
		match 'leave_administrators/update', :to => 'leave_administrators#update', :via => [:get, :post], as: :leave_administrators_update
		match 'leave_administrators/clear', :to => 'leave_administrators#clear', :via => [:get], as: :leave_administrators_clear
	end

	get '/leave_approvals', :to => 'leave_approvals#index'
	get '/leave_timeline', :to => 'leave_timelines#show'
	get '/projects/:project_id/leave_timeline', :to => 'leave_timelines#show_project'
	get '/leave_management_rules/:project_id/show_metrics', :to => 'leave_management_rules#show_metrics', as: :leave_rules_show_metrics

	get '/leave_feedbacks/new', :to => 'leave_requests#feedback_new', as: :leave_feedbacks_new
	post '/leave_feedbacks/send', :to => 'leave_requests#feedback_send', as: :leave_feedbacks_send

	
end

app/models/leave_preference.rb
class LeavePreference < ActiveRecord::Base
  unloadable
  include Redmine::Utils::DateCalculation
  include LeavesHolidaysLogic

  # before_validation :set_user

  default_scope { 
    joins(:user).where(users: {status: 1}) }

  belongs_to :user
  attr_accessible :weekly_working_hours, :annual_leave_days_max, :region, :user_id, :contract_start_date, :contract_end_date, :extra_leave_days, :is_contractor,:annual_max_comments,:leave_renewal_date, :pending_day_count, :overall_percent_alloc, :can_create_leave_requests


  validates :weekly_working_hours, presence: true, numericality: true, inclusion: { in: 0..80}
  validates :annual_leave_days_max, presence: true, numericality: true, inclusion: { in: 0..365}
  validates :contract_start_date, presence: true, date: true
  validates :contract_end_date, date: true

  validates :leave_renewal_date, presence: true, date: true

  validates :extra_leave_days, presence: true, numericality: true, inclusion: { in: -365..365}
  validates :pending_day_count, numericality: true, inclusion: { in: -365..365}
  validates :region, presence: true
  validates :user_id, presence: true
  validates :is_contractor, :inclusion => {:in => [true, false]}

  validates :overall_percent_alloc, numericality: true, inclusion: { in: 0..100}

  validate :validate_region
  validate :validate_contract_end_date

  scope :for_user, ->(uid) { where(user_id: uid) }

  before_save :perform_event_backup, :on => [:create, :update]
  before_save :handle_incorrect_region, :on => [:update]

  def css_classes
    s = "leave-preference user-#{self.user_id}"
    s << ' needs-attention' if self.id && self.pending_day_count && self.pending_day_count != 0
    return s
  end

  def is_region_valid?
    return region.to_sym.in?(Holidays.regions)
  end

  private

  def default_days_leaves_months
  	return annual_leave_days_max.to_f / 12.0
  end

  def daily_working_hours
    return LeavesHolidaysLogic.user_params(user, :weekly_working_hours).to_f / (7.0 - non_working_week_days.count )
  end

  def validate_region
  	regions = RedmineLeavesHolidays::Setting.defaults_settings(:available_regions)
  	unless regions.include?(self.region)
  		errors.add(:region, "is invalid")
  	end 
  end

  def validate_contract_end_date
    if contract_start_date && contract_end_date
      if contract_start_date > contract_end_date
        errors.add(:contract_end_date, "cannot be > to contract start date")
      end
    end
  end

  def perform_event_backup
    leave_pref = self.user.leave_preferences
    event_count = LeaveEvent.where(user_id: self.user_id).count
    if event_count == 0
      event = LeaveEvent.new(user_id: self.user_id, event_type: "initial_backup", comments: "Initial backup before first changes")
      event.event_data = leave_pref.attributes
      event.save
    end
  end

  def handle_incorrect_region
    if is_region_valid?
      former_lp = self.user.leave_preferences
      unless former_lp.is_region_valid?
        LeaveRequest.for_user(self.user_id).where(region: former_lp.region).update_all(region: self.region)
      end
    end
  end


end

app/controllers/leave_preferences_controller.rb
class LeavePreferencesController < ApplicationController
  unloadable
  include LeavesHolidaysLogic
  include LeavesHolidaysPermissions

  helper :leave_requests
  include LeaveRequestsHelper
  
  before_action :set_user
  before_action :set_user_preferences, except: [:index, :bulk_edit, :bulk_update, :clear_filters]
  before_action :authenticate#, except: [:show, :notification]
  before_action :set_holidays, only: [:new, :create, :edit, :bulk_edit, :update, :bulk_update]

  def clear_filters
      remove_filters
      redirect_to leave_preferences_path
  end

  def index
    @limit = per_page_option

    if params[:commit] && params[:commit] == "apply"
      remove_filters
    end

    @projects_initial = Project.all.active    
    if params[:projects].present?
      @projects_selected = @projects_initial.where(id: params[:projects])
      @user.pref[:leave_preference_filters_projects] = params[:projects]
      @user.preference.save
    else
      @projects_selected = @projects_initial.where(id: @user.pref[:leave_preference_filters_projects]) if @user.pref[:leave_preference_filters_projects].present?
    end

    projects = @projects_initial
    projects = @projects_selected if @projects_selected


    @roles_initial = Role.all.givable
    if params[:roles].present?
      @roles_selected = params[:roles]
      @user.pref[:leave_preference_filters_roles] = params[:roles]
      @user.preference.save
    else
      @roles_selected = @user.pref[:leave_preference_filters_roles] if @user.pref[:leave_preference_filters_roles].present?
    end

    roles = @roles_initial
    roles = Role.where(id: @roles_selected) if @roles_selected
    

    @users_initial = LeavesHolidaysLogic.users_for_projects(@projects_initial)

    @regions_initial = @users_initial.joins(:leave_preference).group("leave_preferences.region").count.to_hash.keys + [RedmineLeavesHolidays::Setting.defaults_settings(:region)]
    @regions_initial = @regions_initial.uniq
    
    if params[:region].present?
      @regions_selected = params[:region]
      @user.pref[:leave_preference_filters_regions] = params[:region]
      @user.preference.save
    else
      @regions_selected = @user.pref[:leave_preference_filters_regions] if @user.pref[:leave_preference_filters_regions].present?
    end


    @users_selected = @users_initial
    @users_selected = @users_initial.like(params[:name]) if params[:name].present?
    @users_selected = @users_selected.with_leave_region(@regions_selected) if @regions_selected
    @users_selected = LeavesHolidaysLogic.users_with_roles_for_projects(roles, projects) & @users_selected
    user_ids = @users_selected.map(&:id)

    @users_count = user_ids.count
    @users_pages = Paginator.new @users_count, @limit, params['page']
    @offset = @users_pages.offset
    @users_selected =  User.where(id: user_ids).order(:firstname, :lastname).limit(@limit).offset(@offset).to_a
  end

  def new
  	if @exists
      redirect_to edit_user_leave_preference_path
  	end
  end

  def create
  	@preference = LeavePreference.new(leave_preference_params) unless @exists
    @preference.user_id = @user_pref.id
  	if @preference.save
      event = LeaveEvent.new(user_id: @user_pref.id, event_type: "user_pref_manual_create", comments: "changed_by: #{User.current.login}")
      event.event_data = @preference.attributes
      event.save
      flash[:notice] = l(:leave_preferences_save_success, :user => @user_pref.name)
  		redirect_to edit_user_leave_preference_path
  	else
  		flash[:error] = l(:leave_preferences_save_error)
  		render :new
  	end
  end

  def show
    @auth_change = authenticate_leave_preferences({action: :edit})
  end

  def edit
  end

  def bulk_edit
    if params.has_key?(:user_ids)
      if params[:user_ids].count == 1
        redirect_to new_user_leave_preference_path(User.find(params[:user_ids])) and return
      else
        users = User.find(params[:user_ids])
        @users_preferences = users.map{|u| u.leave_preferences}
      end
    else
      flash[:warning] = l(:leave_preferences_warning_bulk_selection) 
      redirect_to leave_preferences_path
    end
  end

  def bulk_update
    users_preferences = User.find(params[:user_ids]).map{|u| u.leave_preferences}
    users_preferences.each do |user_pref|
      success = user_pref.update_attributes(params[:preferences].reject { |k,v| v.blank? })
      if !success 
        flash[:error] = l(:leave_preferences_save_error)
        redirect_to :controller => 'leave_preferences', :action => 'bulk_edit', :user_ids => params[:user_ids] and return
      else
        event = LeaveEvent.new(user_id: user_pref.user_id, event_type: "user_pref_manual_update", comments: "changed_by: #{User.current.login}")
        event.event_data = user_pref.attributes
        event.save
      end
    end
    flash[:notice] = l(:leave_preferences_bulk_save_success)
    redirect_to leave_preferences_path
  end

  def update
    @preference.user_id = @user_pref.id
  	success = @preference.update(leave_preference_params)
      
    respond_to do |format|
      format.html { 
        if !success 
          flash[:error] = l(:leave_preferences_save_error)
          render :edit
        else
          event = LeaveEvent.new(user_id: @user_pref.id, event_type: "user_pref_manual_update", comments: "changed_by: #{User.current.login}")
          event.event_data = @preference.attributes
          event.save
          flash[:notice] = l(:leave_preferences_save_success, :user => @user_pref.name)
          redirect_to edit_user_leave_preference_path
        end
      }
      format.js
    end
  end

  def destroy
    event = LeaveEvent.new(user_id: @user_pref.id, event_type: "user_pref_deleted", comments: "changed_by: #{User.current.login}")
    event.event_data = @preference.attributes
    event.save
  	@preference.destroy
  	redirect_to edit_user_leave_preference_path
  end

  def notification
  end

  def manage_pending_days
    if params[:accept] && params[:accept].in?(["false", "true"])
      if params[:accept] == "true"
        @preference.extra_leave_days += @preference.pending_day_count
      end
      @preference.pending_day_count = 0.0
      @preference.save
      event = LeaveEvent.new(user_id: @user_pref.id, event_type: "user_pref_manual_update", comments: "changed_by: #{User.current.login}")
      event.event_data = @preference.attributes
      event.save
    end
    redirect_to edit_user_leave_preference_path
  end

private

  def leave_preference_params
  	params.require(:leave_preference).permit(:user_id, :weekly_working_hours, :annual_leave_days_max, :region, :contract_start_date, :contract_end_date, :extra_leave_days, :is_contractor, :annual_max_comments, :leave_renewal_date, :overall_percent_alloc, :can_create_leave_requests)
  end

  def set_user
      @user = User.current
  end

  def set_user_preferences
      @user_pref = User.find(params[:user_id])
      @preference = @user_pref.leave_preferences
      @exists = (@preference.id != nil)
  end

  def set_holidays
	  @regions = LeavesHolidaysLogic.get_region_list
  end

  def remove_filters
    @user.pref[:leave_preference_filters_projects] = nil
    @user.pref[:leave_preference_filters_roles] = nil
    @user.pref[:leave_preference_filters_regions] = nil
    @user.pref[:leave_preference_filters_users] = nil
    @user.preference.save
  end

  def authenticate
    @auth_preferences = authenticate_leave_preferences(params)
    render_403 unless @auth_preferences
  end
end

app/views/leave_preferences/_form_preference.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'leaves_holidays', :plugin => 'redmine_leaves_holidays' %>
<% end %>

<h3><%= l(:leave_preferences_form_title, :user => user_pref.name ) %>:</h3>

<%= form_for [user_pref, preference], :url => user_leave_preference_path, :remote => false do |f| %>
<div class="splitcontentleft">
<div class="members box">
		<% if preference.errors.any? %>
			<div class="flash">
				<ul>
			  		<% preference.errors.full_messages.each do |msg| %>
			    		<li><%= msg %></li>
			  		<% end %>
				</ul>
			</div>
		<% end %>

		<% if user_pref.can_create_leave_requests %>
			<p>
				<label><%= l(:leave_preferences_ref_weekly_working_hours) %>:</label>
				<%= f.number_field :weekly_working_hours, in: 0.0..100.0, step: 0.1 %>
			</p>

			<p>
				<label><%= l(:leave_preferences_overall_alloc) %>:</label>
				<%= f.number_field :overall_percent_alloc, in: 0..100, step: 5 %> % (Full time: 100%, part time: 50%...)
			</p>

			<p>
				<label><%= l(:leave_preferences_holidays_region) %>:</label>
				<%- options = @regions -%>
				<%= f.select :region, options %>
				<% unless preference.is_region_valid? %>
					<strong style="color: red;"><%= l(:leave_preferences_holidays_region_invalid, :region => preference.region) %></strong>
				<% end %>
			</p>

			<% unless user_pref.is_contractor %>
				<p>
					<label><%= l(:leave_preferences_holidays_entitlement_max) %>:</label>
					<%= f.number_field :annual_leave_days_max, in: 0.0..100.0, step: 0.5 %>
				</p>

				<% if preference.pending_day_count && preference.pending_day_count != 0 %>
				<p><strong>
					<%= l(:leave_preferences_user_has_days_to_carry_over, :days => preference.pending_day_count) %>: 
					<%= link_to l(:leave_accept), manage_pending_days_user_leave_preference_path(accept: true), :class => 'icon icon-checked' %>
					<%= link_to l(:leave_discard), manage_pending_days_user_leave_preference_path(accept: false), :class => 'icon icon-unchecked' %>
				</strong></p>
				<% end %>

				<p>
					<label><%= l(:leave_preferences_extra_days) %>:</label>
					<%= f.number_field :extra_leave_days, in: -100.0..100.0, step: 0.5 %>
				</p>

				<p>
					<label><%= l(:leave_preferences_extra_days_comments) %>:</label>
				</p>
				<p>
					<%= f.text_area  :annual_max_comments, cols: "30", rows: "10" %>
				</p>
			<% end %>

			<p>
				<label><%= l(:leave_preferences_contract_start) %>:</label>
				<%= f.text_field :contract_start_date, readonly: true %><%= calendar_for('leave_preference_contract_start_date') %>
			</p>
			
			<p>
				<label><%= l(:leave_preferences_contract_end) %>:</label>
				<%= f.text_field :contract_end_date %><%= calendar_for('leave_preference_contract_end_date') %>
			</p>

			<p>
				<label><%= l(:leave_preferences_leave_renewal_date) %>:</label>
				<%= f.text_field :leave_renewal_date, readonly: true %><%= calendar_for('leave_preference_leave_renewal_date') %>
			</p>

			<p>
				<label><%= t(:leave_preferences_user_is_contractor_html) %>:</label>
				<%= f.check_box :is_contractor %>
			</p>

		<% end %>

		<p>
			<label><%= l(:leave_preferences_user_can_create_leave_requests) %>:</label>
			<%= f.check_box :can_create_leave_requests %>
		</p>

		<%= f.submit l(:button_save) %>


	
<% end %>

| <%= link_to l(:leave_preferences_back_link), leave_preferences_path %> |

<% if @exists %>
	<%= link_to l(:leave_revert_to_defaults), user_leave_preference_path(user_pref), method: :delete, data: { confirm: l(:leave_confirm_dialog) }, :class => "icon icon-del" %>
<% end %>
</div>
</div>

<% if user_pref.can_create_leave_requests %>
	<div id="splitcontentright">
		<%= render partial: '/leave_requests/details_metrics', locals: {user: user_pref} %>
	</div>

	<% events = LeaveEvent.unscoped.for_user(user_pref.id).order(created_at: :desc, id: :desc) %>

	<% unless events.empty? %>
	
<hr/>
	<h3><%= l(:label_history) %>:</h3>
	<div class="autoscroll">
			<table class="list">
				<thead>
				<tr>
				<th><%= l(:leave_date) %></th>
				<th><%= l(:leave_preferences_event_type) %></th>
				<th><%= l(:leave_preferences_event_comments) %></th>
				<th><%= l(:leave_preferences_ref_weekly_working_hours) %></th>
				<th><%= l(:leave_preferences_holidays_entitlement_max) %></th>
				<th><%= l(:leave_preferences_holidays_region) %></th>
				<th><%= l(:leave_preferences_extra_days) %></th>
				<th><%= l(:leave_preferences_pending_days) %></th>
				<th><%= l(:leave_preferences_extra_days_comments) %></th>
				<th><%= l(:leave_preferences_contract_start) %></th>
				<th><%= l(:leave_preferences_contract_end_short) %></th>
				<th><%= l(:leave_preferences_leave_renewal_date_short) %></th>
				<th><%= l(:leave_preferences_user_is_contractor_short) %></th>
				<th><%= l(:leave_preferences_overall_alloc) %></th>
				<th><%= l(:leave_preferences_user_can_create_leave_requests) %></th>
				</tr>
				</thead>
				<tbody>
					<% for event in events -%>
						<% if event.event_data %>
						<% preference = LeavePreference.new(event.event_data) %>
							<tr class="<%= cycle("odd", "even") %>">
							<td><%= event.created_at %></td>
							<td><%= event.event_type %></td>
							<td><%= event.comments %></td>
							<td><%= preference.weekly_working_hours %></td>
							<td><%= preference.annual_leave_days_max %></td>
							<td><%= preference.region %></td>
							<td><%= preference.extra_leave_days %></td>
							<td><%= preference.pending_day_count %></td>
							<td><%= preference.annual_max_comments %></td>
							<td><%= preference.contract_start_date %></td>
							<td><%= preference.contract_end_date %></td>
							<td><%= preference.leave_renewal_date %></td>
							<td><%= preference.is_contractor %></td>
							<td><%= preference.overall_percent_alloc %></td>
							<td><%= preference.can_create_leave_requests %></td>
							</tr>
						<% end %>
					<% end -%>
				</tbody>
			</table>
			</div>
	<% end %>
<% end %>

app/views/leave_preferences/_tab_preferences.html.erb
<%= form_tag(bulk_edit_leave_preferences_path) do %>

<div class="autoscroll">
	<table class="list">
		<thead>
			<tr>
				<th>
					<%= button_tag(type: 'submit', class: "btn btn-primary", title: l(:leave_tab_prefs_edit_bulk_edit)) do %>
 						<i class="icon icon-edit"></i>
					<% end %>
				</th>
				<th><%= l(:leave_user) %></th>
				<th><%= l(:leave_tab_prefs_main_projects) %></th>
				<th><%= l(:leave_tab_prefs_region) %></th>
				<th><%= l(:leave_tab_prefs_contract_start) %></th>
				<th><%= l(:leave_tab_prefs_period_start) %></th>
				<th><%= l(:leave_tab_prefs_period_end) %></th>
				<th><%= l(:leave_tab_prefs_days_max) %></th>
				<th title="<%= l(:leave_tab_prefs_days_max_comments_hint) %>" style="cursor: help;"><%= l(:leave_tab_prefs_days_extra) %></th>
				<th><%= l(:leave_tab_prefs_remaining) %></th>
				<th><%= l(:leave_tab_prefs_accumulated) %></th>
				<th><%= l(:leave_tab_prefs_taken) %></th>
				<th><%= l(:leave_tab_prefs_hours_per_week) %></th>
				<th><%= l(:leave_tab_prefs_percent_alloc) %></th>
				<th><%= l(:leave_tab_prefs_is_contractor) %></th>
			</tr>
		</thead>
		<tbody>
			<% lm = LeavesHolidaysLogic.leave_metrics_for_users(users) %>
			<% lm.each do |u, v| %>
				<% lp = v[:leave_preferences] %>
				<tr class="hascontextmenu <%= cycle("odd", "even") %> <%= lp.css_classes %>">
				<td class="checkbox hide-when-print"><%= check_box_tag("user_ids[]", u.id, false, :id => nil) %>
				</td>
				<td><%= link_to u.name, edit_user_leave_preference_path(u), :class => 'icon icon-edit', :title => l(:leave_tab_prefs_link_edit_help, :user => u.name) %>  <%= link_to '', notification_user_leave_preference_path(u), :class => 'icon icon-help',:title => l(:leave_tab_prefs_link_check_help) %></td>
				<td><div style="min-width: 400px" ><%= user_projects(u) %></div></td>
				<td><%= lp.region %></td>
				<td><%= format_date(lp.contract_start_date) %></td>
				<td><%= format_date(v[:leave_period][:start]) %></td>
				<td><%= format_date(v[:leave_period][:end]) %></td>
				
				<% unless lp.is_contractor %>
					<td title="<%= l(:leave_tab_prefs_actual_entitlement) %>" style="cursor: help;"><%= v[:actual_days_max] %></td>
					<td title="<%= l(:leave_comments) %>: <%= lp.annual_max_comments %>" style="cursor: help;"><%= lp.extra_leave_days %></td>
					<td><%= v[:days_remaining] %></td>
				<% else %>
					<td title="<%= l(:leave_tab_prefs_user_contractor) %>" style="cursor: help;">-</td>
					<td title="<%= l(:leave_tab_prefs_user_contractor) %>" style="cursor: help;">-</td>
					<td title="<%= l(:leave_tab_prefs_user_contractor) %>" style="cursor: help;">-</td>
				<% end %>
				<td><%= v[:days_accumulated] %></td>
				<td><%= v[:days_taken] %></td>
				<td><%= lp.weekly_working_hours %></td>
				<td><%= lp.overall_percent_alloc %></td>
				<td><%= checked_image lp.is_contractor %></td>
				</tr>


			<% end %>
		
		</tbody>
	</table>
</div>
<p class="pagination"><%= pagination_links_full @users_pages, @users_count %></p>
<% end -%>

<%= javascript_tag do %>
$(document).ready(function(){
	//if( !document.attachEvent){
$('table').floatThead({
    position: 'absolute',
    scrollContainer: function($table){
        return $table.closest(".wrapper");
    }
});
	//}
});

<% end %>

app/views/leave_preferences/bulk_edit.html.erb
<h3><%= l(:leave_preferences_bulk_edit_for) %> <%= @users_preferences.map{|p| p.user.login}.join(', ') %></h3>
<div class="box">
<%= form_for :preferences, :url => bulk_update_leave_preferences_path, :method => :put do |f| %>
	<% for user_preference in @users_preferences %>
		<%= hidden_field_tag "user_ids[]", user_preference.user_id %>
	<% end %>

		<p>
			<label><%= l(:leave_preferences_ref_weekly_working_hours) %>:</label>
			<%= f.number_field :weekly_working_hours, in: 0.0..100.0, step: 0.1, :placeholder => l(:label_no_change_option) %>
		</p>

		<p>
			<label><%= l(:leave_preferences_overall_alloc) %>:</label>
			<%= f.number_field :overall_percent_alloc, in: 0..100, step: 5 %> % <%= l(:leave_preferences_overall_alloc_hint) %>
		</p>

		<p>
			<label><%= l(:leave_preferences_holidays_entitlement_max) %>:</label>
			<%= f.text_field :annual_leave_days_max, :placeholder => l(:label_no_change_option) %>
		</p>

		<p>
			<label><%= l(:leave_preferences_holidays_region) %>:</label>
			<%- options = @regions -%>
			<%= f.select :region, options, :include_blank => l(:label_no_change_option) %>
		</p>

		<p>
			<label><%= l(:leave_preferences_extra_days) %>:</label>
			<%= f.text_field :extra_leave_days, :placeholder => l(:label_no_change_option) %>
		</p>

		<p>
			<label><%= l(:leave_preferences_extra_days_comments) %>:</label>
			<%= f.text_field :annual_max_comments, :placeholder => l(:label_no_change_option) %>
		</p>

		<p>
			<label><%= l(:leave_preferences_contract_start) %>:</label>
			<%= f.text_field :contract_start_date, readonly: true, :placeholder => l(:label_no_change_option) %>
			<%= calendar_for('preferences_contract_start_date') %>
		</p>

		<p>
			<label><%= l(:leave_preferences_leave_renewal_date) %>:</label>
			<%= f.text_field :leave_renewal_date, readonly: true, :placeholder => l(:label_no_change_option) %>
			<%= calendar_for('preferences_leave_renewal_date') %>
		</p>

		<p>
			<label><%= t(:leave_preferences_user_is_contractor_html) %>:</label>
			<%- options = [['No', 0],['Yes',1]] -%>
			<%= f.select :is_contractor, options, :include_blank => l(:label_no_change_option)  %>
		</p>

		<p>
			<label><%= l(:leave_preferences_user_can_create_leave_requests) %>:</label>
			<%- options = [['No', 0],['Yes',1]] -%>
			<%= f.select :can_create_leave_requests, options, :include_blank => l(:label_no_change_option)  %>
		</p>

		<p><%= f.submit l(:button_submit) %> | <%= link_to l(:leave_preferences_back_link), leave_preferences_path %> </p>

<% end %>
</div>

app/views/leave_preferences/edit.html.erb
<%= render 'form_preference', user: @user, user_pref: @user_pref, preference: @preference %>

app/views/leave_preferences/index.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'leaves_holidays', :plugin => 'redmine_leaves_holidays' %>
    <%= javascript_include_tag "https://cdnjs.cloudflare.com/ajax/libs/floatthead/1.3.2/jquery.floatThead.min.js" %>
<% end %>



<div class="tabular2"><%= render_leave_tabs leaves_holidays_tabs %></div>

<fieldset><legend><%= l(:leave_filters) %> <small><%= l(:leave_hint_ctrl_clic) %></small></legend>
	<%= form_tag leave_preferences_path, :method => :get do %>

		<label for='projects'><%= l(:field_project) %>:</label>
		<%= select_tag 'projects', leave_projects_options_for_select(@projects_selected), :class => "small", :multiple => true %>
		<label for='Roles'><%= l(:label_role_plural) %>:</label>
		<%= select_tag 'roles', leave_roles_options_for_select(@roles_selected), :class => "small", :multiple => true  %>

    <label for='region'><%= l(:leave_region) %>:</label>
    <%= select_tag 'region', options_for_select(@regions_initial, @regions_selected), :class => "small", :multiple => true  %>

    <label for='name'><%= l(:label_user) %>:</label>
    <%= text_field_tag 'name', params[:name], :size => 30 %>

		<%= submit_tag l(:button_apply), :class => "small", :value => "apply" %>
		<%= link_to l(:button_clear), clear_filters_leave_preferences_path, :class => 'icon icon-reload' %>
	<% end %>
</fieldset>
<br/>
<%= render 'tab_preferences', :users => @users_selected %>

app/views/leave_preferences/new.html.erb
<%= render 'form_preference', user: @user, user_pref: @user_pref, preference: @preference %>

app/views/leave_preferences/update.js.erb
$("#leave_user_prefs").html("<%= escape_javascript(render partial: '/leave_requests/details_metrics', locals: {user: @user_pref}) %>")